#ifndef PROCEDIMIENTOS_H_INCLUDED
#define PROCEDIMIENTOS_H_INCLUDED
//ENUM
enum Zona{norte=1,sur=2,este=3,oeste=4,centro=5};
typedef enum Zona ZONA;
//PROCEDIMIENTO PARA SALIR DEL MENU
void Salir();
//PROCEDIMIENTO PARA ELEGIR LA ZONA CON MENU
ZONA ElegirZona();



#endif // PROCEDIMIENTOS_H_INCLUDED
